import ContactIcon, {ContactIconProps} from '@/components/ContactIcon'

export const Contact_list: ContactIconProps[] = [
  { id: 0, url: 'chi.jpg', name: 'Chi', text: 'Ana sift lik wahd tmrin' },
  { id: 1, url: 'Edward.jpeg', name: 'Edward', text: 'Chri lia Parfum' },
  { id: 2, url: 'logo.png', name: 'iChat', text: 'Hi new user' },
  { id: 3, url: 'Mamadou.jpeg', name: 'Mamadou', text: 'Jib lia marlboro' },
  { id: 4, url: 'edward.jpeg', name: 'Sophie', text: 'Did you see the latest episode?' },
  { id: 5, url: 'chi.jpg', name: 'Liam', text: 'Let’s catch up this weekend.' },
  { id: 6, url: 'logo.png', name: 'Ava', text: 'Don’t forget the meeting at 3!' },
  { id: 7, url: 'Edward.jpeg', name: 'Noah', text: 'I sent the files over.' },
  { id: 8, url: 'Mamadou.jpeg', name: 'Olivia', text: 'Happy Birthday! 🎉' },
  { id: 9, url: 'chi.jpg', name: 'Mason', text: 'Can you call me when you’re free?' },
  { id: 10, url: 'edward.jpeg', name: 'Emma', text: 'Loved your post today!' },
  { id: 11, url: 'edward.jpeg', name: 'Lucas', text: 'Let’s start the project tomorrow.' },
  { id: 12, url: 'logo.png', name: 'Isabella', text: 'Lunch at 1?' },
  { id: 13, url: 'edward.jpeg', name: 'James', text: 'Great job on the demo!' },
  { id: 14, url: 'chi.jpg', name: 'Zara', text: 'Can you review my PR?' },
  { id: 15, url: 'Edward.jpeg', name: 'Ethan', text: 'I’m stuck on this bug again.' },
  { id: 16, url: 'Mamadou.jpeg', name: 'Mila', text: 'Missed the train again 😞' },
  { id: 17, url: 'edward.jpeg', name: 'Leo', text: 'Free for a game later?' },
  { id: 18, url: 'logo.png', name: 'Harper', text: 'New song is fire 🔥' },
  { id: 19, url: 'chi.jpg', name: 'Benjamin', text: 'Do we need a meeting for that?' },
  { id: 20, url: 'Edward.jpeg', name: 'Elijah', text: 'I’ll send the report by 6.' },
  { id: 21, url: 'Mamadou.jpeg', name: 'Aria', text: 'Let’s grab coffee.' },
  { id: 22, url: 'edward.jpeg', name: 'Henry', text: 'I can’t find the file 😕' },
  { id: 23, url: 'chi.jpg', name: 'Chloe', text: 'This made me laugh 😂' },
  { id: 24, url: 'logo.png', name: 'Sebastian', text: 'Back from vacation!' },
  { id: 25, url: 'Edward.jpeg', name: 'Grace', text: 'Team call at 4?' },
  { id: 26, url: 'Mamadou.jpeg', name: 'Jack', text: 'Just landed safely.' },
  { id: 27, url: 'edward.jpeg', name: 'Scarlett', text: 'Want to go hiking?' },
  { id: 28, url: 'chi.jpg', name: 'Daniel', text: 'Love the redesign!' },
  { id: 29, url: 'logo.png', name: 'Layla', text: 'How’s the baby doing?' },
  { id: 30, url: 'Edward.jpeg', name: 'Matthew', text: 'See you at lunch 🍜' },
  { id: 31, url: 'Mamadou.jpeg', name: 'Ella', text: 'Rainy day vibes ☔️' },
  { id: 32, url: 'edward.jpeg', name: 'Aiden', text: 'Don’t forget my charger!' },
  { id: 33, url: 'chi.jpg', name: 'Luna', text: 'Running late 😅' },
  { id: 34, url: 'logo.png', name: 'Wyatt', text: 'The cat is on the keyboard 🐱' },
  { id: 35, url: 'Edward.jpeg', name: 'Nora', text: 'Dinner at 8?' },
  { id: 36, url: 'Mamadou.jpeg', name: 'Julian', text: 'Almost there!' },
  { id: 37, url: 'edward.jpeg', name: 'Camila', text: 'Need help with code review' },
  { id: 38, url: 'chi.jpg', name: 'Leo', text: 'Sending love ❤️' },
  { id: 39, url: 'logo.png', name: 'Victoria', text: 'New ideas brewing ☕️' },
  { id: 40, url: 'Edward.jpeg', name: 'Ezra', text: 'Traffic is crazy today.' },
  { id: 41, url: 'Mamadou.jpeg', name: 'Aurora', text: 'Finished the slides.' },
  { id: 42, url: 'edward.jpeg', name: 'Grayson', text: 'Big news coming up!' },
  { id: 43, url: 'chi.jpg', name: 'Lily', text: 'Your plant is dying 😬' },
  { id: 44, url: 'logo.png', name: 'Isaac', text: 'Let’s play Valorant?' },
  { id: 45, url: 'Edward.jpeg', name: 'Santiago', text: 'Loved that playlist.' },
  { id: 46, url: 'Mamadou.jpeg', name: 'Penelope', text: 'Wanna join my stream?' },
  { id: 47, url: 'edward.jpeg', name: 'Anthony', text: 'Call me when you can.' },
  { id: 48, url: 'chi.jpg', name: 'Naomi', text: 'Let’s bake cookies 🍪' },
  { id: 49, url: 'logo.png', name: 'Gabriel', text: 'The meeting got moved.' },
  { id: 50, url: 'Edward.jpeg', name: 'Hazel', text: 'New book recommendation?' },
  { id: 51, url: 'Mamadou.jpeg', name: 'Lincoln', text: 'Final draft is ready.' },
  { id: 52, url: 'edward.jpeg', name: 'Ellie', text: 'So proud of you 💖' },
  { id: 53, url: 'chi.jpg', name: 'David', text: 'Heading out now.' },
  { id: 54, url: 'logo.png', name: 'Claire', text: 'Don’t forget the milk 🥛' },
  { id: 55, url: 'Edward.jpeg', name: 'Nolan', text: 'Just aced the interview!' },
  { id: 56, url: 'Mamadou.jpeg', name: 'Riley', text: 'New art drop today 🎨' },
  { id: 57, url: 'edward.jpeg', name: 'Paisley', text: 'You coming tonight?' },
  { id: 58, url: 'chi.jpg', name: 'Connor', text: 'Be there in 5' },
  { id: 59, url: 'logo.png', name: 'Brooklyn', text: 'Tell me everything!' }
];
